const actionTypes = Object.freeze({
   //app
   APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
   SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
   CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

   //user
   ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
   USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
   USER_LOGIN_FAIL: ' USER_LOGIN_FAIL',
   PROCESS_LOGOUT: 'PROCESS_LOGOUT',

   CREATE_USER_FAILED: 'CREATE_USER_FAILED',
   CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

   DELETE_USER_FAILED: 'DELETE_USER_FAILED',
   DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

   UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
   UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

   FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
   FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',

   FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
   FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

   FETCH_All_DOCTORS_SUCCESS: 'FETCH_All_DOCTORS_SUCCESS',
   FETCH_All_DOCTORS_FAILED: 'FETCH_All_DOCTORS_FAILED',

   CREATE_DOCTOR_INFO_SUCCEED: 'CREATE_DOCTOR_INFO_SUCCEED',
   CREATE_DOCTOR_INFO_FAILED: 'CREATE_DOCTOR_INFO_FAILED',
});

export default actionTypes;
